### ISSUE TITLE
Got error with Dummy Gateway

### ISSUE THREAD

**Issue by yaser2490** [damcclean/simple-commerce#853]
### Description

Hi
i got error with Dummy Gateway after click on finish and pay !

![Screenshot 2023-03-14 142417](https://user-images.githubusercontent.com/70744366/224979861-caecaadb-88b0-46fa-8c05-3175a02435d1.png)

### Steps to reproduce

fresh install

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.12
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: StataBit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.5.8

**Comment by duncanmcclean** [comment]
Hello!

I think this might have been a bug in the Starter Kit. If you either create a new site using the starter kit OR copy the changes from [this commit](https://github.com/duncanmcclean/sc-starter-kit/commit/1cd2fbc2a87cf554ffaf846d3f56ad85d67753f0) into your site, it should hopefully resolve the problem for you.

**Comment by yaser2490** [comment]
Thanks, the error is solved.

**Comment by sdussaut** [comment]
Hello!
I installed Simple Commerce (5.9.1) today (15/01/24) using the starter kit and the error is still there unfortunately.
It seems the `else` close pointed out in the commit is not present in the code.
By using it, it fixed the problem.

**Comment by duncanmcclean** [comment]
> Hello! I installed Simple Commerce (5.9.1) today (15/01/24) using the starter kit and the error is still there unfortunately. It seems the `else` close pointed out in the commit is not present in the code. By using it, it fixed the problem.

Thanks for pointing that out, it must have been unintentionally removed at some point. I'll get it fixed.
